sudo: required
services:
  - docker

before_install:
  - docker build -t aakashc137/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aakashc137/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-476114130291"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
